version: '3'

services:

  linux:
    image: build-zotero-client:latest
    container_name: build-zotero-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./zotero/:/zotero:rw
    environment:
      - DISPLAY=${DISPLAY}
      - PLATFORM=l
      - DEBUGGER=0
    network_mode: "host"

# More info: https://www.zotero.org/support/dev/client_coding/building_the_desktop_app
